spring:
  application:
    name: java-portfolio-core
  datasource:
    url: jdbc:postgresql://localhost:5432/us_stock_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
server:
  port: 8080
